#ifndef GUARD_CONSTANTS_HEAL_LOCATIONS_H
#define GUARD_CONSTANTS_HEAL_LOCATIONS_H

// Placeholder - heal locations should be generated from map data

#define HEAL_LOCATION_NONE 0
#define HEAL_LOCATION_PALLET_TOWN 1
#define HEAL_LOCATION_VIRIDIAN_CITY 2
#define HEAL_LOCATION_PEWTER_CITY 3
#define HEAL_LOCATION_CERULEAN_CITY 4
#define HEAL_LOCATION_LAVENDER_TOWN 5
#define HEAL_LOCATION_VERMILION_CITY 6
#define HEAL_LOCATION_CELADON_CITY 7
#define HEAL_LOCATION_FUCHSIA_CITY 8
#define HEAL_LOCATION_CINNABAR_ISLAND 9
#define HEAL_LOCATION_INDIGO_PLATEAU 10
#define HEAL_LOCATION_SAFFRON_CITY 11
#define HEAL_LOCATION_ROUTE4 12
#define HEAL_LOCATION_ROUTE10 13
#define HEAL_LOCATION_ONE_ISLAND 14
#define HEAL_LOCATION_TWO_ISLAND 15
#define HEAL_LOCATION_THREE_ISLAND 16
#define HEAL_LOCATION_FOUR_ISLAND 17
#define HEAL_LOCATION_FIVE_ISLAND 18
#define HEAL_LOCATION_SIX_ISLAND 19
#define HEAL_LOCATION_SEVEN_ISLAND 20

/* Rows in sHealLocations[]; must match data/heal_locations.h / heal_locations.json. */
#define HEAL_LOCATION_COUNT 20

#endif // GUARD_CONSTANTS_HEAL_LOCATIONS_H
