"""
Single Python mirror of overworld map-visual policy in `include/fieldmap.h`,
`include/constants/map_grid_block_word.h` (block-word metatile field), and related headers.

**Direction D / Project B tooling:** change C macros first, then update this module and run
`python -m py_compile tools/portable_generators/validate_*.py` and layout block validators.

Consumers include: `validate_*` scripts in this folder, `validate_map_layout_rom_packs.py`,
`tools/validate_map_layout_block_bin.py`, **`tools/validate_field_map_logical_to_physical_inc.py`**,
**`tools/check_project_c_block_word_offline.py`**, **`tools/check_project_c_phase3_offline.py`**.

Not imported by the GBA build — offline validators and generators only.
"""

from __future__ import annotations

# --- Tile / metatile counts (fieldmap.h NUM_TILES_* / compiled NUM_METATILES_*) ---
NUM_TILES_IN_PRIMARY = 640
NUM_TILES_TOTAL = 1024
NUM_METATILES_IN_PRIMARY = NUM_TILES_IN_PRIMARY
# Compiled tileset metatile **table** rows (640 primary + 384 secondary); not map-grid id space.
NUM_METATILES_TOTAL = NUM_TILES_TOTAL
NUM_METATILES_IN_SECONDARY = NUM_METATILES_TOTAL - NUM_METATILES_IN_PRIMARY

# Map **grid** encoded metatile ids (Phase 2 RAM): 0 .. MAP_GRID_METATILE_ID_SPACE_SIZE - 1
MAP_GRID_METATILE_PRIMARY_COUNT = NUM_METATILES_IN_PRIMARY
MAP_GRID_METATILE_ID_SPACE_SIZE = 2048
MAP_GRID_METATILE_SECONDARY_COUNT = MAP_GRID_METATILE_ID_SPACE_SIZE - MAP_GRID_METATILE_PRIMARY_COUNT

# --- Char VRAM span (fieldmap.h MAP_BG_FIELD_TILE_*) ---
TILE_SIZE_4BPP = 32
MAP_BG_FIELD_TILE_CHAR_CAPACITY = NUM_TILES_TOTAL
MAP_BG_FIELD_TILESET_CHAR_VRAM_BYTES = MAP_BG_FIELD_TILE_CHAR_CAPACITY * TILE_SIZE_4BPP
MAP_BG_FIELD_TILESET_MAX_TILE_INDEX = NUM_TILES_TOTAL - 1  # standard 10-bit tilemap TID ceiling
# Door scratch tiles at end of combined field index space (fieldmap.h MAP_BG_FIELD_DOOR_TILE_RESERVED_*).
MAP_BG_FIELD_DOOR_TILE_RESERVED_COUNT = 8
MAP_BG_FIELD_DOOR_TILE_RESERVED_FIRST = MAP_BG_FIELD_TILE_CHAR_CAPACITY - MAP_BG_FIELD_DOOR_TILE_RESERVED_COUNT

DEFAULT_PRI_UNCOMPRESSED_BYTES = NUM_TILES_IN_PRIMARY * TILE_SIZE_4BPP
DEFAULT_SEC_UNCOMPRESSED_BYTES = NUM_METATILES_IN_SECONDARY * TILE_SIZE_4BPP

# --- Metatile graphics blobs (8 u16 per metatile) — vanilla **compiled** row counts ---
BYTES_PER_METATILE_GFX = 8 * 2
DEFAULT_PRIMARY_METATILE_GFX_BYTES = NUM_METATILES_IN_PRIMARY * BYTES_PER_METATILE_GFX
DEFAULT_SECONDARY_METATILE_GFX_BYTES = NUM_METATILES_IN_SECONDARY * BYTES_PER_METATILE_GFX
MAP_BG_MAX_PRI_GFX_BYTES = DEFAULT_PRIMARY_METATILE_GFX_BYTES
MAP_BG_MAX_SEC_GFX_BYTES = DEFAULT_SECONDARY_METATILE_GFX_BYTES

# --- Metatile attribute blobs (u32 per metatile) ---
METATILE_ATTR_BYTES_PER = 4
DEFAULT_PRIMARY_METATILE_ATTR_BYTES = NUM_METATILES_IN_PRIMARY * METATILE_ATTR_BYTES_PER
DEFAULT_SECONDARY_METATILE_ATTR_BYTES = NUM_METATILES_IN_SECONDARY * METATILE_ATTR_BYTES_PER

# --- Compiled asset profile extended bounds (validate_compiled_tileset_asset_profile_directory) ---
METATILE_GFX_UNIT = BYTES_PER_METATILE_GFX
METATILE_GFX_MIN_NONZERO = NUM_METATILES_IN_SECONDARY * METATILE_GFX_UNIT
# Upper bound: 2048 metatile rows worth of gfx (validator contract; map grid encoded space)
METATILE_GFX_MAX_METATILES = 2048
METATILE_GFX_MAX = METATILE_GFX_MAX_METATILES * METATILE_GFX_UNIT

METATILE_ATTR_UNIT = METATILE_ATTR_BYTES_PER
METATILE_ATTR_MIN_NONZERO = NUM_METATILES_IN_SECONDARY * METATILE_ATTR_UNIT
METATILE_ATTR_MAX = METATILE_GFX_MAX_METATILES * METATILE_ATTR_UNIT

# --- Palette bundle (NUM_PALS_TOTAL = 13 vanilla) ---
NUM_PALS_TOTAL = 13
VANILLA_PALETTE_BUNDLE_BYTES = NUM_PALS_TOTAL * TILE_SIZE_4BPP
PALETTE_BUNDLE_MAX_BYTES = 256 * TILE_SIZE_4BPP

# --- PRET on-disk wire V1 (`map.bin` / `border.bin`) ---
MAP_GRID_BLOCK_WORD_WIRE_V1_METATILE_ID_MASK = 0x03FF
MAP_GRID_BLOCK_WORD_WIRE_V1_COLLISION_MASK = 0x0C00
MAP_GRID_BLOCK_WORD_WIRE_V1_ELEVATION_MASK = 0xF000
MAP_GRID_BLOCK_WORD_WIRE_V1_COLLISION_SHIFT = 10
MAP_GRID_BLOCK_WORD_WIRE_V1_ELEVATION_SHIFT = 12
# Exclusive max metatile id in wire V1 (10 bits).
DEFAULT_WIRE_V1_METATILE_ID_LIMIT_EXCLUSIVE = 1024

# --- Phase 2 RAM (`MAPGRID_*` / live map / migrated `mapView`) ---
MAP_GRID_BLOCK_WORD_LAYOUT_VANILLA = 1
MAP_GRID_BLOCK_WORD_LAYOUT_PHASE2_U16 = 2
MAP_GRID_BLOCK_WORD_METATILE_ID_MASK = 0x07FF
MAP_GRID_BLOCK_WORD_COLLISION_MASK = 0x1800
MAP_GRID_BLOCK_WORD_ELEVATION_MASK = 0xE000
MAP_GRID_BLOCK_WORD_COLLISION_SHIFT = 11
MAP_GRID_BLOCK_WORD_ELEVATION_SHIFT = 13
MAP_GRID_BLOCK_WORD_ENCODED_METATILE_COUNT = MAP_GRID_METATILE_ID_SPACE_SIZE
DEFAULT_MAP_GRID_METATILE_ID_LIMIT_EXCLUSIVE = DEFAULT_WIRE_V1_METATILE_ID_LIMIT_EXCLUSIVE

# --- Phase 3 planned on-disk `u32` cell (tooling / future runtime; vanilla stays u16 wire V1) ---
MAP_GRID_BLOCK_WORD_LAYOUT_PHASE3_U32 = 3
MAP_GRID_BLOCK_WORD_PHASE3_U32_METATILE_ID_MASK = 0x0000FFFF
MAP_GRID_BLOCK_WORD_PHASE3_U32_COLLISION_MASK = 0x00030000
MAP_GRID_BLOCK_WORD_PHASE3_U32_ELEVATION_MASK = 0x001C0000
MAP_GRID_BLOCK_WORD_PHASE3_U32_COLLISION_SHIFT = 16
MAP_GRID_BLOCK_WORD_PHASE3_U32_ELEVATION_SHIFT = 18
MAP_GRID_BLOCK_WORD_PHASE3_U32_ENCODED_METATILE_COUNT = 65536
DEFAULT_PHASE3_U32_METATILE_ID_LIMIT_EXCLUSIVE = MAP_GRID_BLOCK_WORD_PHASE3_U32_ENCODED_METATILE_COUNT
