#ifndef GUARD_FIRERED_PORTABLE_ROM_MAP_HEADER_SCALARS_H
#define GUARD_FIRERED_PORTABLE_ROM_MAP_HEADER_SCALARS_H

#include "map_header_scalars_access.h"

#endif /* GUARD_FIRERED_PORTABLE_ROM_MAP_HEADER_SCALARS_H */
