#ifndef GUARD_FIRERED_PORTABLE_ROM_REGION_MAP_SECTION_GRIDS_H
#define GUARD_FIRERED_PORTABLE_ROM_REGION_MAP_SECTION_GRIDS_H

void firered_portable_rom_region_map_section_grids_refresh_after_rom_load(void);

#endif /* GUARD_FIRERED_PORTABLE_ROM_REGION_MAP_SECTION_GRIDS_H */
