#ifndef GUARD_FIRERED_PORTABLE_ROM_TRAINER_MONEY_TABLE_H
#define GUARD_FIRERED_PORTABLE_ROM_TRAINER_MONEY_TABLE_H

void firered_portable_rom_trainer_money_table_refresh_after_rom_load(void);

#endif /* GUARD_FIRERED_PORTABLE_ROM_TRAINER_MONEY_TABLE_H */
