#ifndef ENGINE_CORE_ENGINE_INTERNAL_H
#define ENGINE_CORE_ENGINE_INTERNAL_H

#include <stddef.h>
#include <stdint.h>

#define ENGINE_GBA_WIDTH 240
#define ENGINE_GBA_HEIGHT 160
#define ENGINE_GBA_RGBA_SIZE (ENGINE_GBA_WIDTH * ENGINE_GBA_HEIGHT * 4)

#define ENGINE_EWRAM_ADDR 0x02000000u
#define ENGINE_EWRAM_SIZE 0x00040000u
#define ENGINE_IWRAM_ADDR 0x03000000u
#define ENGINE_IWRAM_SIZE 0x00008000u
#define ENGINE_IOREG_ADDR 0x04000000u
#define ENGINE_IOREG_SIZE 0x00000400u
#define ENGINE_PALETTE_ADDR 0x05000000u
#define ENGINE_PALETTE_SIZE 0x00000400u
#define ENGINE_VRAM_ADDR 0x06000000u
#define ENGINE_VRAM_SIZE 0x00018000u
#define ENGINE_OAM_ADDR 0x07000000u
#define ENGINE_OAM_SIZE 0x00000400u
#define ENGINE_ROM_ADDR 0x08000000u
#define ENGINE_ROM_SIZE 0x02000000u
#define ENGINE_SRAM_ADDR 0x0E000000u
#define ENGINE_SRAM_SIZE 0x00020000u

#define ENGINE_REG_DISPCNT 0x04000000u
#define ENGINE_REG_BG0CNT 0x04000008u
#define ENGINE_REG_BG1CNT 0x0400000Au
#define ENGINE_REG_BG2CNT 0x0400000Cu
#define ENGINE_REG_BG3CNT 0x0400000Eu
#define ENGINE_REG_BG0HOFS 0x04000010u
#define ENGINE_REG_BG0VOFS 0x04000012u
#define ENGINE_REG_BG1HOFS 0x04000014u
#define ENGINE_REG_BG1VOFS 0x04000016u
#define ENGINE_REG_BG2HOFS 0x04000018u
#define ENGINE_REG_BG2VOFS 0x0400001Au
#define ENGINE_REG_BG3HOFS 0x0400001Cu
#define ENGINE_REG_BG3VOFS 0x0400001Eu
#define ENGINE_REG_WIN0H 0x04000040u
#define ENGINE_REG_WIN1H 0x04000042u
#define ENGINE_REG_WIN0V 0x04000044u
#define ENGINE_REG_WIN1V 0x04000046u
#define ENGINE_REG_WININ 0x04000048u
#define ENGINE_REG_WINOUT 0x0400004Au
#define ENGINE_REG_BLDCNT 0x04000050u
#define ENGINE_REG_BLDALPHA 0x04000052u
#define ENGINE_REG_BLDY 0x04000054u
#define ENGINE_REG_KEYINPUT 0x04000130u

#define ENGINE_DISPCNT_FORCED_BLANK 0x0080u
#define ENGINE_DISPCNT_BG0_ON 0x0100u
#define ENGINE_DISPCNT_BG1_ON 0x0200u
#define ENGINE_DISPCNT_BG2_ON 0x0400u
#define ENGINE_DISPCNT_BG3_ON 0x0800u
#define ENGINE_DISPCNT_OBJ_ON 0x1000u
#define ENGINE_DISPCNT_WIN0_ON 0x2000u
#define ENGINE_DISPCNT_WIN1_ON 0x4000u
#define ENGINE_DISPCNT_OBJWIN_ON 0x8000u
#define ENGINE_DISPCNT_OBJ_1D_MAP 0x0040u

typedef struct EngineOAMEntry {
    uint16_t attr0;
    uint16_t attr1;
    uint16_t attr2;
    int16_t affine_param;
} EngineOAMEntry;

#define FIRERED_GBA_WIDTH ENGINE_GBA_WIDTH
#define FIRERED_GBA_HEIGHT ENGINE_GBA_HEIGHT
#define FIRERED_GBA_RGBA_SIZE ENGINE_GBA_RGBA_SIZE
#define FIRERED_EWRAM_ADDR ENGINE_EWRAM_ADDR
#define FIRERED_EWRAM_SIZE ENGINE_EWRAM_SIZE
#define FIRERED_IWRAM_ADDR ENGINE_IWRAM_ADDR
#define FIRERED_IWRAM_SIZE ENGINE_IWRAM_SIZE
#define FIRERED_IOREG_ADDR ENGINE_IOREG_ADDR
#define FIRERED_IOREG_SIZE ENGINE_IOREG_SIZE
#define FIRERED_PALETTE_ADDR ENGINE_PALETTE_ADDR
#define FIRERED_PALETTE_SIZE ENGINE_PALETTE_SIZE
#define FIRERED_VRAM_ADDR ENGINE_VRAM_ADDR
#define FIRERED_VRAM_SIZE ENGINE_VRAM_SIZE
#define FIRERED_OAM_ADDR ENGINE_OAM_ADDR
#define FIRERED_OAM_SIZE ENGINE_OAM_SIZE
#define FIRERED_ROM_ADDR ENGINE_ROM_ADDR
#define FIRERED_ROM_SIZE ENGINE_ROM_SIZE
#define FIRERED_SRAM_ADDR ENGINE_SRAM_ADDR
#define FIRERED_SRAM_SIZE ENGINE_SRAM_SIZE
#define FIRERED_REG_DISPCNT ENGINE_REG_DISPCNT
#define FIRERED_REG_BG0CNT ENGINE_REG_BG0CNT
#define FIRERED_REG_BG1CNT ENGINE_REG_BG1CNT
#define FIRERED_REG_BG2CNT ENGINE_REG_BG2CNT
#define FIRERED_REG_BG3CNT ENGINE_REG_BG3CNT
#define FIRERED_REG_BG0HOFS ENGINE_REG_BG0HOFS
#define FIRERED_REG_BG0VOFS ENGINE_REG_BG0VOFS
#define FIRERED_REG_BG1HOFS ENGINE_REG_BG1HOFS
#define FIRERED_REG_BG1VOFS ENGINE_REG_BG1VOFS
#define FIRERED_REG_BG2HOFS ENGINE_REG_BG2HOFS
#define FIRERED_REG_BG2VOFS ENGINE_REG_BG2VOFS
#define FIRERED_REG_BG3HOFS ENGINE_REG_BG3HOFS
#define FIRERED_REG_BG3VOFS ENGINE_REG_BG3VOFS
#define FIRERED_REG_WIN0H ENGINE_REG_WIN0H
#define FIRERED_REG_WIN1H ENGINE_REG_WIN1H
#define FIRERED_REG_WIN0V ENGINE_REG_WIN0V
#define FIRERED_REG_WIN1V ENGINE_REG_WIN1V
#define FIRERED_REG_WININ ENGINE_REG_WININ
#define FIRERED_REG_WINOUT ENGINE_REG_WINOUT
#define FIRERED_REG_BLDCNT ENGINE_REG_BLDCNT
#define FIRERED_REG_BLDALPHA ENGINE_REG_BLDALPHA
#define FIRERED_REG_BLDY ENGINE_REG_BLDY
#define FIRERED_REG_KEYINPUT ENGINE_REG_KEYINPUT
#define FIRERED_DISPCNT_FORCED_BLANK ENGINE_DISPCNT_FORCED_BLANK
#define FIRERED_DISPCNT_BG0_ON ENGINE_DISPCNT_BG0_ON
#define FIRERED_DISPCNT_BG1_ON ENGINE_DISPCNT_BG1_ON
#define FIRERED_DISPCNT_BG2_ON ENGINE_DISPCNT_BG2_ON
#define FIRERED_DISPCNT_BG3_ON ENGINE_DISPCNT_BG3_ON
#define FIRERED_DISPCNT_OBJ_ON ENGINE_DISPCNT_OBJ_ON
#define FIRERED_DISPCNT_WIN0_ON ENGINE_DISPCNT_WIN0_ON
#define FIRERED_DISPCNT_WIN1_ON ENGINE_DISPCNT_WIN1_ON
#define FIRERED_DISPCNT_OBJWIN_ON ENGINE_DISPCNT_OBJWIN_ON
#define FIRERED_DISPCNT_OBJ_1D_MAP ENGINE_DISPCNT_OBJ_1D_MAP
#define FireredOAMEntry EngineOAMEntry

int engine_memory_init(const uint8_t *rom, size_t rom_size);
void engine_memory_shutdown(void);

void engine_backend_input_reset(void);
void engine_backend_input_set_buttons(uint16_t buttons);

void engine_video_reset(void);
void engine_video_render_frame(void);
const uint8_t *engine_video_get_framebuffer(void);

void engine_audio_reset(void);
int16_t *engine_audio_get_samples(size_t *count);
void engine_audio_submit_pcm(const int16_t *samples, size_t count);
void engine_audio_submit_gba_directsound(const int8_t *fifo_a, const int8_t *fifo_b, size_t sample_count);

#endif
