#!/usr/bin/env python3
"""
generate_map_headers.py - Generate map_groups.h from data/maps/ directory

This script scans the data/maps directory and generates the required
constants/map_groups.h header file with all MAP_ constants.
"""

import os
import json
from pathlib import Path
from collections import defaultdict

def generate_map_headers(data_dir: Path, output_dir: Path):
    """Generate map_groups.h from map data files."""
    
    maps_dir = data_dir / "maps"
    groups_file = data_dir / "map_groups.json"
    
    # Read map groups definition
    if not groups_file.exists():
        print(f"Warning: {groups_file} not found, using default grouping")
        # Create default group structure
        map_groups = defaultdict(list)
        for map_dir in sorted(maps_dir.iterdir()):
            if map_dir.is_dir():
                map_name = map_dir.name
                group_name = "gMapGroup_" + map_name.split('_')[0] if '_' in map_name else "gMapGroup_Other"
                map_groups[group_name].append(map_name)
    else:
        with open(groups_file, 'r') as f:
            groups_data = json.load(f)
        
        map_groups = defaultdict(list)
        for group_name, maps_list in groups_data.items():
            if isinstance(maps_list, list):
                map_groups[group_name] = maps_list
    
    # Generate map_groups.h content
    lines = [
        "#ifndef GUARD_CONSTANTS_MAP_GROUPS_H",
        "#define GUARD_CONSTANTS_MAP_GROUPS_H",
        "",
        "// Auto-generated by generate_map_headers.py",
        "// Do not edit manually",
        "",
        "// Map constants",
        "#define MAP_UNDEFINED (0xFF | (0xFF << 8))",
        "#define MAP_DYNAMIC (0x7F | (0x7F << 8))",
        "",
    ]
    
    # Generate MAP_ constants
    all_maps = []
    group_id = 0
    
    for group_name in sorted(map_groups.keys()):
        maps_in_group = map_groups[group_name]
        
        lines.append(f"// {group_name}")
        
        for map_idx, map_name in enumerate(maps_in_group):
            map_id = (group_id << 8) | map_idx
            constant_name = f"MAP_{map_name.upper()}"
            lines.append(f"#define {constant_name} 0x{map_id:04X}")
            all_maps.append((map_name, constant_name, group_id, map_idx))
        
        lines.append("")
        group_id += 1
    
    # Add map count
    lines.append(f"#define MAP_COUNT {len(all_maps)}")
    lines.append("")
    lines.append("#endif // GUARD_CONSTANTS_MAP_GROUPS_H")
    
    # Write output
    output_path = output_dir / "map_groups.h"
    output_dir.mkdir(parents=True, exist_ok=True)
    
    with open(output_path, 'w') as f:
        f.write('\n'.join(lines))
    
    print(f"Generated {output_path}")
    print(f"  Total maps: {len(all_maps)}")
    print(f"  Map groups: {group_id}")
    
    return len(all_maps)

def main():
    import sys
    
    # Default paths
    data_dir = Path("D:/Godot/pokefirered-master/data")
    output_dir = Path("D:/Godot/pokefirered-master/include/constants")
    
    if len(sys.argv) > 1:
        data_dir = Path(sys.argv[1])
    if len(sys.argv) > 2:
        output_dir = Path(sys.argv[2])
    
    print("=" * 60)
    print("Map Headers Generator")
    print("=" * 60)
    print(f"Data directory: {data_dir}")
    print(f"Output directory: {output_dir}")
    print("=" * 60)
    
    count = generate_map_headers(data_dir, output_dir)
    
    print(f"\nSuccess! Generated constants for {count} maps.")
    return 0

if __name__ == "__main__":
    exit(main())
