#!/usr/bin/env python3
"""
generate_localid_constants.py - Generate LOCALID_ constants from map data
"""

import json
import re
from pathlib import Path
from collections import defaultdict

def extract_localids(map_file):
    """Extract all LOCALID_ constants from a map.json file."""
    localids = set()
    
    try:
        with open(map_file, 'r') as f:
            content = f.read()
        
        # Find all LOCALID_ references
        matches = re.findall(r'LOCALID_\w+', content)
        localids.update(matches)
        
    except Exception as e:
        print(f"Warning: Could not read {map_file}: {e}")
    
    return localids

def generate_localid_header(data_dir, output_file):
    """Generate map_event_ids.h with all LOCALID constants."""
    
    maps_dir = Path(data_dir) / "maps"
    all_localids = set()
    
    # Scan all map files
    for map_file in maps_dir.rglob("map.json"):
        localids = extract_localids(map_file)
        all_localids.update(localids)
    
    # Sort for consistent output
    sorted_localids = sorted(all_localids)
    
    # Generate header content
    lines = [
        "#ifndef GUARD_CONSTANTS_MAP_EVENT_IDS_H",
        "#define GUARD_CONSTANTS_MAP_EVENT_IDS_H",
        "",
        "// Auto-generated by generate_localid_constants.py",
        "// Do not edit manually",
        "",
        f"// Total unique LOCALID constants: {len(sorted_localids)}",
        "",
    ]
    
    # Assign values sequentially
    for i, localid in enumerate(sorted_localids):
        lines.append(f"#define {localid} {i}")
    
    lines.extend([
        "",
        "#endif // GUARD_CONSTANTS_MAP_EVENT_IDS_H"
    ])
    
    # Write output
    with open(output_file, 'w') as f:
        f.write('\n'.join(lines))
    
    print(f"Generated {output_file}")
    print(f"  Total LOCALID constants: {len(sorted_localids)}")
    
    return len(sorted_localids)

def main():
    data_dir = Path("D:/Godot/pokefirered-master/data")
    output_file = Path("D:/Godot/pokefirered-master/include/constants/map_event_ids.h")
    
    print("=" * 60)
    print("LOCALID Constants Generator")
    print("=" * 60)
    print(f"Data directory: {data_dir}")
    print(f"Output file: {output_file}")
    print("=" * 60)
    
    count = generate_localid_header(data_dir, output_file)
    
    print(f"\nSuccess! Generated {count} LOCALID constants.")
    return 0

if __name__ == "__main__":
    exit(main())
