#!/usr/bin/env python3
"""
rom_offset_mapper.py - Maps assets to ROM offsets

This script attempts to determine GBA ROM offsets for assets using multiple methods:
1. Build-time: Parse ld_script.ld or build artifacts for linked addresses
2. Runtime discovery: Generate offsets.json with placeholder values for runtime scanning

Since pokefirered is a full decompilation, asset offsets can theoretically be determined
from the build system. However, if that's not available, we support runtime discovery
where the game scans the user's ROM at first launch.
"""

import os
import re
import json
import argparse
import struct
from pathlib import Path
from typing import List, Dict, Optional, Tuple


def load_asset_registry(registry_path: Path) -> List[Dict]:
    """Load the asset registry generated by incbin_transform.py"""
    with open(registry_path, 'r', encoding='utf-8') as f:
        return json.load(f)


def try_parse_ld_script(ld_script_path: Path) -> Dict[str, int]:
    """
    Attempt to parse the linker script for asset addresses.
    
    Returns dict mapping symbol names to ROM offsets.
    """
    offsets = {}
    
    if not ld_script_path.exists():
        return offsets
    
    try:
        with open(ld_script_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # Look for symbol definitions in linker script
        # Pattern: symbol = 0xXXXXXXXX; or symbol : ORIGIN + length
        symbol_pattern = re.compile(r'(\w+)\s*=\s*(0x[0-9a-fA-F]+)', re.IGNORECASE)
        
        for match in symbol_pattern.finditer(content):
            symbol = match.group(1)
            addr = int(match.group(2), 16)
            # Convert to ROM offset (GBA ROM starts at 0x08000000)
            if addr >= 0x08000000:
                offsets[symbol] = addr - 0x08000000
        
    except Exception as e:
        print(f"Warning: Could not parse ld_script: {e}")
    
    return offsets


def try_extract_from_symfile(sym_path: Path) -> Dict[str, int]:
    """
    Attempt to extract offsets from a symbol file (.sym or similar).
    
    pokefirered builds typically generate .sym files with address information.
    """
    offsets = {}
    
    if not sym_path.exists():
        return offsets
    
    try:
        with open(sym_path, 'r', encoding='utf-8') as f:
            for line in f:
                # Common symbol file format: ADDR TYPE NAME
                # Example: 08012345 T sBagWindowPalF
                parts = line.strip().split()
                if len(parts) >= 3:
                    try:
                        addr = int(parts[0], 16)
                        symbol = parts[2]
                        if addr >= 0x08000000:
                            offsets[symbol] = addr - 0x08000000
                    except ValueError:
                        pass
    except Exception as e:
        print(f"Warning: Could not parse symbol file: {e}")
    
    return offsets


def get_asset_binary_size(asset_path: Path) -> int:
    """Get the size of an asset file in bytes."""
    try:
        return asset_path.stat().st_size
    except:
        return 0


def varname_to_symbol_guess(varname: str, asset_path: str) -> str:
    """
    Convert variable name to likely symbol name.
    
    In pokefirered, symbols often match the variable name directly,
    or follow specific naming conventions.
    """
    # Most commonly, the symbol name IS the variable name
    return varname


def scan_rom_for_asset(
    rom_data: bytes,
    asset_data: bytes,
    alignment: int = 4
) -> Optional[int]:
    """
    Scan ROM data for a specific asset by binary fingerprint.
    
    Args:
        rom_data: Full ROM binary
        asset_data: Asset binary data to search for
        alignment: Byte alignment requirement (default 4)
    
    Returns:
        ROM offset if found, None otherwise
    """
    if len(asset_data) < 4:
        # Too short to reliably fingerprint
        return None
    
    # Use first 32 bytes or full asset as fingerprint
    fingerprint = asset_data[:min(32, len(asset_data))]
    
    # Scan ROM for fingerprint
    pos = 0
    while True:
        pos = rom_data.find(fingerprint, pos)
        if pos == -1:
            break
        
        # Verify alignment
        if pos % alignment == 0:
            # Found a match - verify full content if reasonable size
            if len(asset_data) <= 256:
                end_pos = pos + len(asset_data)
                if end_pos <= len(rom_data):
                    if rom_data[pos:end_pos] == asset_data:
                        return pos
            else:
                # For larger assets, first 32 bytes match is good enough
                return pos
        
        pos += 1
    
    return None


def try_find_offsets_from_assets(
    registry: List[Dict],
    graphics_root: Path,
    rom_data: Optional[bytes] = None
) -> Dict[str, Dict]:
    """
    Try to find ROM offsets by scanning asset binaries.
    
    If rom_data is provided, scans the ROM for asset fingerprints.
    Otherwise, marks for runtime discovery.
    """
    results = {}
    
    for entry in registry:
        varname = entry['varname']
        asset_path_str = entry['asset_path']
        asset_type = entry['type']
        
        # Build full path to asset
        asset_path = graphics_root / asset_path_str
        
        if not asset_path.exists():
            print(f"  Warning: Asset not found: {asset_path}")
            results[varname] = {
                'varname': varname,
                'type': asset_type,
                'rom_offset': None,
                'size_bytes': 0,
                'status': 'asset_not_found',
                'asset_path': asset_path_str
            }
            continue
        
        size = get_asset_binary_size(asset_path)
        
        if rom_data:
            # Try to find in ROM
            with open(asset_path, 'rb') as f:
                asset_data = f.read()
            
            offset = scan_rom_for_asset(rom_data, asset_data)
            
            if offset is not None:
                results[varname] = {
                    'varname': varname,
                    'type': asset_type,
                    'rom_offset': offset,
                    'size_bytes': size,
                    'status': 'found_in_rom',
                    'asset_path': asset_path_str
                }
            else:
                results[varname] = {
                    'varname': varname,
                    'type': asset_type,
                    'rom_offset': None,
                    'size_bytes': size,
                    'status': 'not_in_provided_rom',
                    'asset_path': asset_path_str
                }
        else:
            # No ROM provided - mark for runtime discovery
            results[varname] = {
                'varname': varname,
                'type': asset_type,
                'rom_offset': None,
                'size_bytes': size,
                'status': 'runtime_discovery_required',
                'asset_path': asset_path_str
            }
    
    return results


def generate_runtime_discovery_code(offsets_data: Dict[str, Dict]) -> str:
    """
    Generate C code for runtime offset discovery.
    
    Creates a function that scans the loaded ROM for assets at startup.
    """
    # This is just documentation - actual implementation is in gba_c_bridge.cpp
    code = '''
// Runtime ROM offset discovery
// This code is auto-generated by rom_offset_mapper.py
// Assets marked for runtime_discovery_required will be scanned at startup

// The actual implementation is in gba_assets_init() in gba_c_bridge.cpp
'''
    return code


def build_offset_database(
    registry_path: Path,
    graphics_root: Path,
    output_path: Path,
    ld_script_path: Optional[Path] = None,
    symfile_path: Optional[Path] = None,
    rom_path: Optional[Path] = None
) -> Tuple[int, int]:
    """
    Build the complete offset database.
    
    Returns:
        (found_count, total_count)
    """
    print("Loading asset registry...")
    registry = load_asset_registry(registry_path)
    print(f"  {len(registry)} assets registered")
    
    offsets = {}
    
    # Method 1: Try linker script
    if ld_script_path and ld_script_path.exists():
        print("\nMethod 1: Parsing linker script...")
        ld_offsets = try_parse_ld_script(ld_script_path)
        print(f"  Found {len(ld_offsets)} symbols in linker script")
        
        for entry in registry:
            varname = entry['varname']
            if varname in ld_offsets:
                asset_path = graphics_root / entry['asset_path']
                size = get_asset_binary_size(asset_path) if asset_path.exists() else 0
                offsets[varname] = {
                    'varname': varname,
                    'type': entry['type'],
                    'rom_offset': ld_offsets[varname],
                    'size_bytes': size,
                    'status': 'from_linker_script',
                    'asset_path': entry['asset_path']
                }
    
    # Method 2: Try symbol file
    if symfile_path and symfile_path.exists():
        print("\nMethod 2: Parsing symbol file...")
        sym_offsets = try_extract_from_symfile(symfile_path)
        print(f"  Found {len(sym_offsets)} symbols in symbol file")
        
        for entry in registry:
            varname = entry['varname']
            if varname in sym_offsets and varname not in offsets:
                asset_path = graphics_root / entry['asset_path']
                size = get_asset_binary_size(asset_path) if asset_path.exists() else 0
                offsets[varname] = {
                    'varname': varname,
                    'type': entry['type'],
                    'rom_offset': sym_offsets[varname],
                    'size_bytes': size,
                    'status': 'from_symbol_file',
                    'asset_path': entry['asset_path']
                }
    
    # Method 3: Binary scanning (with or without ROM)
    print("\nMethod 3: Asset binary scanning...")
    rom_data = None
    if rom_path and rom_path.exists():
        print(f"  Loading ROM: {rom_path}")
        with open(rom_path, 'rb') as f:
            rom_data = f.read()
        print(f"  ROM size: {len(rom_data)} bytes")
    
    # Get remaining entries that need offset discovery
    remaining = [e for e in registry if e['varname'] not in offsets]
    if remaining:
        discovered = try_find_offsets_from_assets(remaining, graphics_root, rom_data)
        offsets.update(discovered)
    
    # Count results
    found = sum(1 for v in offsets.values() if v.get('rom_offset') is not None)
    total = len(registry)
    
    # Generate output
    output_list = list(offsets.values())
    
    # Sort by source file for readability
    output_list.sort(key=lambda x: x.get('asset_path', ''))
    
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(output_list, f, indent=2)
    
    return found, total


def generate_embedded_header(offsets_path: Path, header_path: Path):
    """
    Generate a C header file with embedded offset data.
    
    This allows the runtime to load offsets without external files.
    """
    with open(offsets_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    # Generate C array with offset data
    lines = [
        '#ifndef GBA_ASSET_OFFSETS_H',
        '#define GBA_ASSET_OFFSETS_H',
        '',
        '// Auto-generated by rom_offset_mapper.py',
        '// Do not edit manually',
        '',
        '#include <stdint.h>',
        '',
        'typedef struct {',
        '    const char* varname;',
        '    uint32_t rom_offset;',
        '    uint32_t size_bytes;',
        '    uint8_t type_size;  // 1=u8, 2=u16, 4=u32',
        '} AssetOffsetEntry;',
        '',
        'static const AssetOffsetEntry g_asset_offsets[] = {'
    ]
    
    type_size_map = {'u8': 1, 'u16': 2, 'u32': 4}
    
    for entry in data:
        varname = entry['varname']
        offset = entry.get('rom_offset', 0)
        size = entry.get('size_bytes', 0)
        type_size = type_size_map.get(entry.get('type', 'u8'), 1)
        
        if offset is None:
            offset = 0xFFFFFFFF  # Marker for runtime discovery
        
        lines.append(f'    {{"{varname}", {offset}, {size}, {type_size}}},')
    
    lines.extend([
        '    {NULL, 0, 0, 0}  // Sentinel',
        '};',
        '',
        '#define ASSET_OFFSET_COUNT ' + str(len(data)),
        '#define OFFSET_RUNTIME_DISCOVERY 0xFFFFFFFF',
        '',
        '#endif /* GBA_ASSET_OFFSETS_H */'
    ])
    
    header_path.parent.mkdir(parents=True, exist_ok=True)
    with open(header_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))


def main():
    parser = argparse.ArgumentParser(
        description='Map pokefirered assets to ROM offsets'
    )
    parser.add_argument(
        '--registry',
        type=Path,
        default=Path('tools/asset_registry.json'),
        help='Path to asset registry JSON (default: tools/asset_registry.json)'
    )
    parser.add_argument(
        '--graphics-root',
        type=Path,
        default=Path('../graphics'),
        help='Root of graphics directory (default: ../graphics)'
    )
    parser.add_argument(
        '--output',
        type=Path,
        default=Path('tools/asset_offsets.json'),
        help='Output JSON file (default: tools/asset_offsets.json)'
    )
    parser.add_argument(
        '--header',
        type=Path,
        default=Path('include/gba_asset_offsets.h'),
        help='Output C header file (default: include/gba_asset_offsets.h)'
    )
    parser.add_argument(
        '--ld-script',
        type=Path,
        help='Path to ld_script.ld for symbol extraction'
    )
    parser.add_argument(
        '--symfile',
        type=Path,
        help='Path to symbol file (.sym) for offset extraction'
    )
    parser.add_argument(
        '--rom',
        type=Path,
        help='Path to GBA ROM for binary fingerprint scanning'
    )
    parser.add_argument(
        '--runtime-discovery',
        action='store_true',
        help='Mark all assets for runtime discovery (no build-time ROM required)'
    )
    
    args = parser.parse_args()
    
    # Ensure paths are absolute
    script_dir = Path(__file__).parent.absolute()
    
    registry_path = (script_dir / args.registry).resolve()
    graphics_root = (script_dir / args.graphics_root).resolve()
    output_path = (script_dir / args.output).resolve()
    header_path = (script_dir / args.header).resolve()
    
    ld_script = (script_dir / args.ld_script).resolve() if args.ld_script else None
    symfile = (script_dir / args.symfile).resolve() if args.symfile else None
    rom_path = None if args.runtime_discovery else (script_dir / args.rom).resolve() if args.rom else None
    
    print("=" * 70)
    print("ROM Offset Mapper for PokeFireRed")
    print("=" * 70)
    print(f"Registry: {registry_path}")
    print(f"Graphics: {graphics_root}")
    print(f"Output:   {output_path}")
    print(f"Header:   {header_path}")
    if ld_script:
        print(f"LD Script: {ld_script}")
    if symfile:
        print(f"Symfile: {symfile}")
    if rom_path:
        print(f"ROM: {rom_path}")
    elif args.runtime_discovery:
        print("Mode: Runtime discovery (all assets)")
    print("=" * 70)
    
    try:
        found, total = build_offset_database(
            registry_path, graphics_root, output_path,
            ld_script, symfile, rom_path
        )
        
        print(f"\nOffset mapping complete:")
        print(f"  Found: {found}/{total} assets ({100*found//total}%)")
        print(f"  Pending runtime discovery: {total - found} assets")
        
        # Generate embedded header
        print(f"\nGenerating embedded header...")
        generate_embedded_header(output_path, header_path)
        print(f"  Written: {header_path}")
        
        return 0
        
    except Exception as e:
        print(f"\nError: {e}")
        import traceback
        traceback.print_exc()
        return 1


if __name__ == '__main__':
    exit(main())
